APIKEY: "asdadasdadada"
# can have many codes or 1, 3 lines put here for example
CODES:
  - ["Shocker 1","aaaaa"]
  - ["Shocker 2","bbbbbb"]
  - ["Shocker 3","ccccccc"]
UNAME: "sdawsdwasdawd"
NICKNAME: "Autoshock-Default"
